### ISSUE TITLE
Full auction table prevents addon from displaying cheapest auctions

### ISSUE THREAD

**Issue by KevinTyrrell** [shirsig/aux-addon-TBC#18]
On Faerlina there are over 3500 auctions of Arcane Dust. Attempting to search this item on Aux yields a 'Table Full' warning, which prevents further auctions from being added to the table.

**Search of Arcane Dust using Aux** (does not display the hundreds of cheapest auctions)

![image](https://user-images.githubusercontent.com/12791400/171775059-d22138bf-84ea-4620-981e-0191e2baa942.png)

**Search of Arcane Dust using TSM** (displays cheapest auctions correctly)

![image](https://user-images.githubusercontent.com/12791400/171775298-6320fc61-3679-44a3-ae2d-abc8281bfa5f.png)

Solution(s):

- Remove the table size limit (likely not a good idea)
- Re-design aux's table implementation. Upon reaching the table's limit, aux should eject auctions out of the table which are the largest (depending on the active sort). For example if the table was `{ 2, 5, 8 }` the table limit was `3`, and `4` is to be added, `8` should be removed in order to make space for `6`, updating the table to `{ 2, 4, 5 }`.

I wouldn't say this is an enhancement or feature, but more so a bug because it prevents the user from selling their goods at prices at sensible prices.  Someone wanting to sell 'Arcane Dust' in this case would be forced to download TSM/Auctionator/etc in order to proceed.

If help with this issue is needed I would be willing to make a pull request, with a bit of instruction on how this interacts with the backend.

**Comment by shirsig** [comment]
The post tab doesn't have this limit as far as I remember so it shouldn't matter for sellers.
As for the search tab, you could add an additional filter like "arcane dust/exact/percent/100" to limit the results to the cheaper ones.
I agree that it would make more sense to drop by selected sorting but I'm afraid I won't have time to implement that anytime soon.
(by the way, this is the repo for private servers tbc)
