### ISSUE TITLE
LUA Error on "Auctions" page

### ISSUE THREAD

**Issue by fuba82** [shirsig/aux-addon-TBC#3]
hi there,

Get this when click on an Item at the "Auctions" page
```
[2017/08/19 04:48:03-366-x1]: aux-addon\core\scan.lua:136: attempt to compare nil with number
(tail call): ?:
(tail call): ?:
aux-addon\control.lua:44: in function <Interface\AddOns\aux-addon\control.lua:26>

  ---
```

**Comment by fuba82** [comment]
fixed in my fork and i did a pull request

**Comment by shirsig** [comment]
Should be fixed now. Completely changed the scanning for bids/auctions (as the API is very different from vanilla and allows for a much nicer implementation)
