### ISSUE TITLE
vendor prices

### ISSUE THREAD

**Issue by kochetkovd** [shirsig/aux-addon-TBC#9]
Hello. Is there any way to import vendor prices? When i played on Nostalrius it was possible to import prices from "Informant" and now vanilla-players have "aux_merchant_prices"

**Comment by mindfuneral** [comment]
Have you done this?:
/aux populate wdb

**Comment by shirsig** [comment]
/aux populate wdb has nothing to do with vendor prices
You can import prices with a script when both addons are loaded but I haven't written one for tbc. maybe someone else has.
